### ISSUE TITLE
New Install comes up with empty Resources page and "Loading"

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#144]
After fresh install ... 
http://localhost:4244/arc/archive.org/details/local?transport=HTTP&mirror=localhost:4244

Proved this on my mac, so its not IIAB specific.

**Comment by mitra42** [comment]
[ ] A: ~/dweb-mirror.config.yaml is 
```
apps:
  crawl:
    tasks: []
```
Which is missing "home", that update was in v0.2.23 which hadn't been pushed to npm.

To fix problem . delete ~/dweb-mirror.config.yaml and update dweb-mirror

**Comment by mitra42** [comment]
[ ] B: ... shouldnt fail if no local resources

[ ] C: Looks like problem with clicking on "home" icon on default install

**Comment by mikerjensen** [comment]
Hmm, can't find  ~/dweb-mirror.config.yaml, and not sure how to 'update dweb-mirror' ... i do see:
/opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror/dweb-mirror.config.yaml
do i remove that one?

**Comment by mitra42** [comment]
Sorry - its in /root/dweb-mirror.config.yaml on IIAB (/root is the home of the user the server runs as )

Though give me a couple of hours, I'm just testing an update that should fix a couple of other things ... THEN 
```
cd /opt/iiab/internetarchive 
sudo yarn upgrade
```
The machine will probably need to restart to restart the server.

**Comment by mitra42** [comment]
All fixed and pushed

**Comment by mitra42** [comment]
@mikerjensen - this means that the full steps to upgrade,  this time is 
```
sudo rm /root/dweb-mirror.config.yaml
cd /opt/iiab/internetarchive
sudo yarn upgrade
service internetarchive restart
```
That last step removes the need to restart the machine

**Comment by mitra42** [comment]
Let me know if you still see the problem
