### ISSUE TITLE
MikeJ: Community Video not showing up

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#149]
@mikerjensen said in https://github.com/iiab/iiab/issues/1576#issuecomment-497245626

> Going to the Community Video page is faster, but only loads the top part of the menu, doesn't show any data...like this:
> Clicking on the 'Collections' menu option option on this page doesn't do anything... the page remains the same.

I'm not seeing this Community Video is working for me ... console logs would be useful, or confirmation if this is not happening any more.

**Comment by mikerjensen** [comment]
This still happening. Similar to the 'Community Media' link - the banner for this section shows up, but nothing after the menu. Console log: 
Download the React DevTools for a better development experience: https://fb.me/react-devtools react.js:6791:17
Successfully compiled asm.js code (total compilation time 3ms) dweb-transports-bundle.js
Successfully compiled asm.js code (total compilation time 1ms) dweb-transports-bundle.js
Hello wonderful person! :) Thanks for using GUN, feel free to ask for help on https://gitter.im/amark/gun and ask StackOverflow questions tagged with 'gun'! dweb-transports-bundle.js:301:13889
dweb-transports Setting up connection to HTTP with options 
Object { statuselement: null, http: {…}, transports: (1) […], paused: [], mirror: "http://box.local:4244" }
 +0ms dweb-transports-bundle.js:31:2726
dweb-transports Connection stage 1 to HTTP +13ms dweb-transports-bundle.js:31:2726
dweb-transports:httptools p_httpfetch: http://box.local:4244/info  +0ms dweb-transports-bundle.js:31:2726
SoundManager V2.97a.20150601 (HTML5-only mode) soundmanager2-jsmin.js:34:36
SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true soundmanager2-jsmin.js:34:36
SoundManager 2: Ready. ✓ soundmanager2-jsmin.js:34:36
dweb-transports Connection stage 2 to HTTP +67ms dweb-transports-bundle.js:31:2726
dweb-transports Connection completed to 
Array [ "HTTP" ]
 +1ms dweb-transports-bundle.js:31:2726
dweb-archive:Nav Navigating to Details opensource_media +0ms dweb-archive-bundle.js:9:144357
dweb-transports Fetching http://box.local:4244/arc/archive.org/metadata/opensource_media via HTTP +97ms dweb-transports-bundle.js:31:2726
dweb-transports:httptools p_httpfetch: http://box.local:4244/arc/archive.org/metadata/opensource_media  +165ms dweb-transports-bundle.js:31:2726
dweb-transports Fetching http://box.local:4244/arc/archive.org/metadata/opensource_media via HTTP succeeded 0 bytes +59ms dweb-transports-bundle.js:31:2726

​

**Comment by mitra42** [comment]
I'm having a real challenge repeating this....

Are you connected to the net at this point, this log looks perfectly correct up to that last point, then its getting success 0 bytes which is odd.
I thought it might be some bug (probably fixed by now, as I haven't seen 0 length files for a while) has cached a 0 length file but when I create a 0-length
`/libraries/archiveorg/opensource_media/opensource_media_meta.json` then the system correctly refetches it.

So ... two questions
a) are you offline or online while doing this test
b) can you get me a `ls -al /libraries/archiveorg/opensource_media` 

THEN to see if this fixes it ... 

Remove any 0 size files 
```
cd /libraries/archiveorg
rm `find . -size 0 -print`
```
Get the latest version
```
cd /opts/iiab/internetarchive 
yarn upgrade
```
And run the (just updated) maintenance process
```
cd /opts/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror
./internetarchive -m 
```

**Comment by mikerjensen** [comment]
Hi, Yes strange. When I looked at it this morning the resolv.conf
      nameserver setting of 127.0.0.1 had stopped working again, so i
      changed it to 8.8.8.8
    which brought the RPI back online, but still the Communiy Video
      page remains unpopulated..
    ls -al /library/archiveorg/opensource_media/
    
    total 48
        drwxr-xr-x   2 root root  4096 May 30 08:44 .
        drwxr-xr-x 179 root root 12288 May 30 09:02 ..
        -rw-r--r--   1 root root  9975 May 30 08:44 __ia_thumb.jpg
        -rw-r--r--   1 root root   208 May 30 08:44
        opensource_media_extra.json
        -rw-r--r--   1 root root  3964 May 30 08:44
        opensource_media_files.json
        -rw-r--r--   1 root root  5427 Jun 14 14:41
        opensource_media_member.json
        -rw-r--r--   1 root root  1157 May 30 08:44
        opensource_media_meta.json
      
    
    
    there were no zero length files in
      /library/archiveorg
    
    
    I did the yarn rebuild, and the banner
      part of the interface changed (new buttons!) so i know that
      worked...but
    
    then running the maintenance process gave the following error below,
    and box.local:4244 won't load at all now
    
    
    Mike
    
    
    root@box:/opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror#
      ./internetarchive -m 
      Hello wonderful person! :) Thanks for using GUN, feel free to ask
      for help on https://gitter.im/amark/gun and ask StackOverflow
      questions tagged with 'gun'!
/opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror/MirrorFS.js:541
                                          errs.push({cacheDirectory,
      relFilePath, new Error("found file ending in .part")});
                                                                               
      ^^^^^
      
      SyntaxError: Unexpected identifier
          at Module._compile (internal/modules/cjs/loader.js:721:23)
          at Object.Module._extensions..js
      (internal/modules/cjs/loader.js:787:10)
          at Module.load (internal/modules/cjs/loader.js:653:32)
          at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
          at Function.Module._load
      (internal/modules/cjs/loader.js:585:3)
          at Module.require (internal/modules/cjs/loader.js:690:17)
          at require (internal/modules/cjs/helpers.js:25:18)
          at Object.<anonymous>
(/opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror/ArchiveItemPatched.js:22:18)
          at Module._compile (internal/modules/cjs/loader.js:776:30)
          at Object.Module._extensions..js
      (internal/modules/cjs/loader.js:787:10)
          at Module.load (internal/modules/cjs/loader.js:653:32)
          at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
          at Function.Module._load
      (internal/modules/cjs/loader.js:585:3)
          at Module.require (internal/modules/cjs/loader.js:690:17)
          at require (internal/modules/cjs/helpers.js:25:18)
          at Object.<anonymous>
(/opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror/internetarchive:21:21)
          at Module._compile (internal/modules/cjs/loader.js:776:30)
          at Object.Module._extensions..js
      (internal/modules/cjs/loader.js:787:10)
          at Module.load (internal/modules/cjs/loader.js:653:32)
          at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
          at Function.Module._load
      (internal/modules/cjs/loader.js:585:3)
          at Function.Module.runMain
      (internal/modules/cjs/loader.js:829:12)
root@box:/opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror#
      
    
    
    
    
    
    
    
    On 14/06/19 04:52, Mitra Ardron wrote:
    
    
      
      I'm having a real challenge repeating this....
      Are you connected to the net at this point, this log looks
        perfectly correct up to that last point, then its getting
        success 0 bytes which is odd.
        I thought it might be some bug (probably fixed by now, as I
        haven't seen 0 length files for a while) has cached a 0 length
        file but when I create a 0-length
        /libraries/archiveorg/opensource_media/opensource_media_meta.json
        then the system correctly refetches it.
      So ... two questions
        a) are you offline or online while doing this test
        b) can you get me a ls -al
          /libraries/archiveorg/opensource_media
      THEN to see if this fixes it ...
      Remove any 0 size files
      cd /libraries/archiveorg
rm `find . -size 0 -print`

      Get the latest version
      cd /opts/iiab/internetarchive 
yarn upgrade

      And run the (just updated) maintenance process
      cd /opts/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror
./internetarchive -m 

      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/internetarchive/dweb-mirror/issues/149?email_source=notifications\u0026email_token=ABOY56R7MEBXNNR3NCWL573P2MIWBA5CNFSM4HSFHKT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXVULCA#issuecomment-501958024",
"url": "https://github.com/internetarchive/dweb-mirror/issues/149?email_source=notifications\u0026email_token=ABOY56R7MEBXNNR3NCWL573P2MIWBA5CNFSM4HSFHKT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXVULCA#issuecomment-501958024",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mitra42** [comment]
OOps - introduced that bug yesterday, fixed on my machine but didn't push it.  Update should work now. 
Hopefully that will fix it, but it seems odd that there are no zero-length files, while its returning one at the last line of your trace, lets try the update and `maintenance` steps, and if that fails then the server log would be good, I think you can get it at `journalctl -u internetarchive` but I'm remote from my RPi at the moment so can't check that.

**Comment by mikerjensen** [comment]
Thanks - for the email -  I think that server log nailed it. Its a bug 
in the archive.org PHP server,  Tracey fixed that in late May, and I 
then took out the workaround in my code on May 30th, but I think you've 
got bad data cached from before that. That's my mistake - I didn't think 
others might have badly cached data.

Can you send me the file 
|/libraries/archiveorg/opensource_media/opensource_media_playlist.json|

|If I'm correct, it will have at least one field with a '%' in it 
(something url encoded that shouldn't have been).
|

|The fix is easy.
|

|cd |||/libraries/archiveorg/
rm */*_playlist.json
||

||That will remove all the potentially bad cached playlists, and it 
should refetch them as soon as they are needed
||

||Thanks again helping me debug these.
||

||- Mitra
||

||
||

**Comment by mitra42** [comment]
@mikerjensen I think we fixed Community Media & Community Video, so closing this
