### ISSUE TITLE
Webtorrent - not working in node

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#15]
See https://github.com/webtorrent/webtorrent/issues/1156 ,
I'm getting  Unsupported tracker protocol: wss://tracker.btorrent.xyz (undefined) trying to run things in node.

**Comment by mitra42** [comment]
Note that Webtorrent will fall back to the File URL so it will still work, but just not be able to retrieve from other peers.

**Comment by jhiesey** [comment]
You need to explicitly choose a module for webrtc support in node. Both `wrtc`(https://github.com/js-platform/node-webrtc) and `electron-webrtc`(https://github.com/mappum/electron-webrtc) are available, but they both have some issues. In particular, `wrtc` is a bit buggy and `electron-webrtc` runs a whole Chrome instance (see its readme).

How to get started:
``` js
const wrtc = require('wrtc') // to use 'wrtc' module
// const wrtc = require('electron-webrtc')() // to use 'electron-webrtc'

const WebTorrent = require('webtorrent')
const wt = new WebTorrent({
    tracker: {
        wrtc
    }
})

// use wt
```

If using `electron-webrtc`, also check out https://github.com/webtorrent/webtorrent-hybrid and https://github.com/webtorrent/webtorrent-hybrid/blob/master/lib/global.js

**Comment by mitra42** [comment]
THanks wrtc seems to work
