### ISSUE TITLE
Store retrieved files in IPFS 

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#23]
See #11 (meta-ipfs)

Once #22 (install) is done, use HTTP API
Notes from @parkan
```
- to use filestore just pass `&nocopy=true` to the http API
```

**Comment by mitra42** [comment]
See https://github.com/internetarchive/dweb-mirror/issues/new

**Comment by mitra42** [comment]
`ipfs add --cid-version=1 --nocopy commute.mp4` gets the same hash as [https://dweb.me/arc/archive.org/metadata/commute/commute.mp4] i.e. `zdj7Wc9BBA2kar84oo8S6VotYc9PySAnmc8ji6kzKAFjqMxHS`

BUT getting a message `Error: cannot add filestore references outside ipfs root`

**Comment by parkan** [comment]
hmm is the file on the same filesystem as the ipfs repo?

**Comment by mitra42** [comment]
No - I found https://github.com/ipfs/go-ipfs/issues/4224 which suggests that is intentional for security reasons (though there are questions that this is a valid solution to a real problem) and you have to symlink between filesystems to make it work (bad idea). And a (better IMHO) suggestion that filestore should read the contents of the file as the user to create the hash.

**Comment by parkan** [comment]
can we walk through this usecase a bit more? 

>  I have (multiple) external hard disks that hold a mirror of some portion of the Internet Archive, and want to add their contents with --nocopy

are these hard disks permanently attached to the computer and mounted? if you intend to plug it in, add the files then unplug, then adding with nocopy is not the right approach

**Comment by mitra42** [comment]
Yes - the case where these would be used would be permanently mounted disks. For example in one of the use cases we are working on there would be 40TB of external disk (based in India) with a sub-set of the IA on it. 

Obviously since this is a generic tool, I wont know the exact setup, so I have to create whatever links etc are required to make access to the disks possible with IPFS (if we are using IPFS). 

As I said elsewhere I'm going to move to urlstore since filestore seems too limited in several ways.

**Comment by parkan** [comment]
my only suggestion here would have been to put mountpoints somewhere inside IPFS root

symlinking across volumes is also not something that I'm aware of being an antipattern (hard-linking is, of course)

**Comment by mitra42** [comment]
Its just an anti-pattern because its sole purpose is to give ipfs access to a volume that it wouldnt have access to for IPFS's reason, so now this other Volume is effectively located within the user's home directory, where it doesn't belong for any otehr reason.

**Comment by mitra42** [comment]
As an update - we its now successfully storing into IPFS from dweb-mirror, which means that any dweb-mirror with IPFS installed can automatically seed anything it crawls. Still some polishing to do, but working.
