### ISSUE TITLE
Platform IIAB: node, yarn, and upgrade verbose and slow

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#235]
Improve speed on IIAB install - especially
- [x] installation of node
- [x] installation of yarn
- [x] yarn upgrade
 
- [x] Once yarn upgrade fast, then add to `internetarchive` role so run after install 
- [x] also see issue #234 re warnings during `yarn upgrade`

**Comment by mitra42** [comment]
Note yarn upgrade (running second time, so should be quick) took 12 mins on a RPI4 with 2GB

**Comment by mitra42** [comment]
Note also there will be an issue to pull IPFS, Gun, Wolk out of dweb-transports dependencies so that can speed install where not used.

**Comment by holta** [comment]
Amazing

@mitra42 can you please review @jvonau 's PR iiab/iiab#1921 ?

**Comment by mitra42** [comment]
MUCH faster now, yarn upgrades/installs depending on existing, and dweb transports omitted unless specified that are going to use them.

**Comment by jvonau** [comment]
More speed enhancements in the works: https://github.com/iiab/iiab/pull/2008/commits/b61105f21f295dff07d7f294a62517fde34ea31b

**Comment by mitra42** [comment]
Other than splittling it into three different files I'm not sure what you've done there, or how it speeds things up. 

How would someone use the ansible role to update internetarchive - currently I tell them (in README.me) to:
```
cd /opt/iiab/internetarchive/node_modules/dweb-mirror
yarn upgrade
```
Which I believe is non-ideal, but is because I don't understand the changes you've made.

**Comment by holta** [comment]
Excellent question!

Thanks @mitra42 & @jvonau for helping us all understand these proposed optimizations/changes...

**Comment by mitra42** [comment]
Hmmm - not sure what you mean adam, I still don't understand what the correct instructions are to update internetarchive

**Comment by holta** [comment]
> Hmmm - not sure what you mean adam, I still don't understand what the correct instructions are to update internetarchive

@mitra42 

Can you suggest a call day/timeframe so we can sync up and @jvonau / others can explain better?

**Comment by holta** [comment]
> @mitra42
> 
> Can you suggest a call day/timeframe so we can sync up and @jvonau / others can explain better?

Whether before or after our IIAB Mini-Summit & Hackathon!

**Comment by holta** [comment]
fyi IIAB Mini-Summit & Hackathon ...is Nov 7-10 in Boston in a few days from now:
https://meta.wikimedia.org/wiki/Internet-in-a-Box/Summit-2019

**Comment by mitra42** [comment]
Unless we do it tomorrow it would be better end of next week as I'm at a conference 6-8th then on a flight back home. I'll be on US time so e.g. 8am NSW / 3pm PT / 6pm ET is probably ideal, and do-able most days.

**Comment by holta** [comment]
Between 10AM and 2PM NYC Time if possible, even if we have to defer towards mid-Nov worst case?

Or ping on Skype "later this morning" Nov 5th if a quick chat helps!
