### ISSUE TITLE
node v12 requires level v5

### ISSUE THREAD

**Issue by JesseWeinstein** [internetarchive/dweb-mirror#236]
While node v10 (the stable version) requires level v4. So if all our platforms support node v12, we can use that -- otherwise, maybe a branch?

**Comment by mitra42** [comment]
I tested level v5 under node v10 and it seemed to work, I don't know why I locked level at v4, it might have been a failure to build, or that I was concerned that the v4.x - v5.x transition would break the API in some way, but a check of their docs suggests the changes don't impact any aspect we are using so I've pushed it up to level v5.
