### ISSUE TITLE
Online status isn't getting updated correctly

### ISSUE THREAD

**Issue by JesseWeinstein** [internetarchive/dweb-mirror#237]
When I go offline, the circle doesn't turn red, even the the console shows failing online checks. I'll investigate more.

**Comment by mitra42** [comment]
- [ ] Nav bar is showing "Connecting" 
- [ ] None of the UI is going to offline state (e.g. the line `About` ... `People` still shows)

**Comment by mitra42** [comment]
RESEARCH
Core function is `ReactSupport.transportStatusAndProps`
This is called from Page.constructor -

**Comment by mitra42** [comment]
CLEAN UP (after bug fixed)
- [ ] Check that Page.constructor called when navigation happens,
       its likely only called once, and may need to be in a ComponentDidMountOrUpdate method

**Comment by mitra42** [comment]
DIAGNOSIS
Running with WiFi on - so should show online (its not) 
- Breakpoint on Page.jsx on call to transportStatusAndProps is being hit
- Breakpoint in callback isn't
- transportStatusAndProps is running 1st line  but not hitting breakpoint after waterfall
- The httpStatus.status test is good, so running the else and going to the P_GET but doesnt appear to call the cb()
- hard to trace as p_GET has a number of overlapping calls.

**Comment by mitra42** [comment]
Obscure ! It was triggering a process called "loopguard" which tries to remove queued http fetches when a page switches. This should have resulted in an error, but the error was being discarded  in httptools.queuedFetch rather than sent back on the callback.

**Comment by mitra42** [comment]
Fixed that but now need to
- [ ] Catch error appropriately
- [ ] Dont trigger a loopguard error either by new NoLoopGuard flag, or explicitly setting req for loopguard or something else 
- [ ] Maybe get info direct from DwebTransports as it has it already

**Comment by mitra42** [comment]
Fixed - and pushed to github and npm
